import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Polyline, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import oakParkLogo from './assets/oak-park-logo.png';
import { apiConfigured, request, residentApi, vendorApi, villageApi } from './api';

type Role = 'resident' | 'vendor' | 'village';
type RecordValue = Record<string, unknown>;
const oakParkCenter: [number, number] = [41.885, -87.785];

function useHashRoute() {
  const [route, setRoute] = useState(() => location.hash.replace(/^#/, '') || '/resident/info');
  useEffect(() => { const update = () => setRoute(location.hash.replace(/^#/, '') || '/resident/info'); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update); }, []);
  return [route, (next: string) => { location.hash = next; }] as const;
}

function useApi<T>(loader: () => Promise<T>, deps: unknown[]) {
  const [state, setState] = useState<{ loading: boolean; data?: T; error?: string }>({ loading: true });
  useEffect(() => {
    let live = true;
    setState({ loading: true });
    loader().then((data) => live && setState({ loading: false, data })).catch((error: unknown) => live && setState({ loading: false, error: error instanceof Error ? error.message : 'Unable to load this data.' }));
    return () => { live = false; };
  // Callers control fetches through stable scalar dependencies.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
  return state;
}

function asRecord(value: unknown): RecordValue { return value && typeof value === 'object' && !Array.isArray(value) ? value as RecordValue : {}; }
function records(value: unknown): RecordValue[] { return Array.isArray(value) ? value.map(asRecord) : []; }
function text(value: unknown, fallback = '—') { return typeof value === 'string' || typeof value === 'number' ? String(value) : fallback; }
function list(value: unknown) { return Array.isArray(value) ? value.map((item) => text(item)).filter((item) => item !== '—') : []; }
function titleCase(value: string) { return value ? value[0].toUpperCase() + value.slice(1) : value; }
function dateText(value: unknown, fallback = '—') { if (typeof value !== 'string') return fallback; const date = new Date(`${value}T12:00:00`); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(date); }

function App() {
  const [route, go] = useHashRoute();
  const role: Role = route.startsWith('/vendor') ? 'vendor' : route.startsWith('/village') ? 'village' : 'resident';
  return <div className="site-shell"><RoleBar role={role} go={go} /><Header role={role} route={route} go={go} /><main>{role === 'resident' ? <Resident route={route} go={go} /> : role === 'vendor' ? <Vendor route={route} go={go} /> : <Village route={route} go={go} />}</main><Footer /></div>;
}

function RoleBar({ role, go }: { role: Role; go: (route: string) => void }) {
  const target = (item: Role) => item === 'resident' ? '/resident/info' : item === 'vendor' ? '/vendor/home' : '/village/requests';
  return <div className="rolebar"><div className="wide"><div className="role-switch" aria-label="Select product view">{(['resident', 'vendor', 'village'] as Role[]).map((item) => <button className={role === item ? 'active' : ''} key={item} onClick={() => go(target(item))}>{titleCase(item)}</button>)}</div></div></div>;
}

function Header({ role, route, go }: { role: Role; route: string; go: (route: string) => void }) {
  const nav: [string, string, boolean][] = role === 'resident' ? [['Info', '/resident/info', false], ['New event', '/resident/new', false], ['My events', '/resident/events', false]] : role === 'vendor' ? [['Home', '/vendor/home', false], ['Matched jobs', '/vendor/matches', false], ['My jobs', '/vendor/jobs', false]] : [['Requests', '/village/requests', false], ['Today', '/village/today', false], ['Visualization', '/village/planner', true]];
  return <header className="main-header"><div className="wide header-inner"><button className="brand" onClick={() => go(nav[0][1])} aria-label="Village of Oak Park"><img src={oakParkLogo} alt="Village of Oak Park" /></button><nav aria-label={`${titleCase(role)} navigation`}>{nav.map(([label, target, smart]) => <button className={`${route === target ? 'active' : ''} ${smart ? 'smart-tab' : ''}`} key={target} onClick={() => go(target)}>{smart && <span aria-hidden="true">✦</span>}{label}</button>)}</nav><button className="logout" title="Sign-out is provided by the connected identity service" onClick={() => go('/resident/info')}>Sign out</button></div></header>;
}

function Footer() { return <footer className="wide">Not an official Village of Oak Park product. Rules shown are 2026; confirm 2027 with Public Works.</footer>; }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
function Button({ children, onClick, variant = 'primary', disabled }: { children: React.ReactNode; onClick?: () => void; variant?: 'primary' | 'secondary' | 'quiet' | 'danger'; disabled?: boolean }) { return <button className={`button ${variant}`} onClick={onClick} disabled={disabled}>{children}</button>; }
function PageIntro({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="page-intro"><div><h1>{title}</h1><p>{text}</p></div>{action}</div>; }
function Status({ value }: { value: unknown }) { const status = typeof value === 'string' ? value.toLowerCase() : 'pending'; return <span className={`badge ${status}`}>{titleCase(status)}</span>; }
function LoadingCard({ label = 'Loading…' }: { label?: string }) { return <Card className="loading-card"><span className="spinner" />{label}</Card>; }
function ApiError({ message }: { message: string }) { return <Card className="api-error"><h2>We couldn’t load this data</h2><p>{message}</p>{!apiConfigured && <p className="muted">Set <code>VITE_API_BASE</code> to the Party in a Box API URL, then reload. No sample records are shown.</p>}</Card>; }

function RealMap({ block, height = 270 }: { block?: RecordValue; height?: number }) {
  const centroid = Array.isArray(block?.centroid) && block?.centroid.length === 2 ? block.centroid as [number, number] : oakParkCenter;
  const lines = Array.isArray(block?.lines) ? block.lines as [number, number][][] : [];
  return <div className="real-map" style={{ height }}><MapContainer center={centroid} zoom={block ? 16 : 14} scrollWheelZoom={false} style={{ height: '100%', width: '100%' }}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{lines.map((line, index) => <Polyline key={index} positions={line} pathOptions={{ color: '#1b745b', weight: 6 }} />)}<CircleMarker center={centroid} radius={8} pathOptions={{ color: '#fff', fillColor: '#1b745b', fillOpacity: 1, weight: 3 }} /></MapContainer></div>;
}

function Resident({ route, go }: { route: string; go: (route: string) => void }) { if (route === '/resident/new') return <NewEvent go={go} />; if (route.startsWith('/resident/petition/')) return <Petition id={route.split('/').pop()!} go={go} />; if (route === '/resident/events') return <MyEvents go={go} />; return <ResidentInfo go={go} />; }

function ResidentInfo({ go }: { go: (route: string) => void }) {
  const rules = useApi(() => residentApi.getRules(2027), []);
  const ruleRows = rules.data ? list(asRecord(rules.data).checklist) : [];
  return <div className="wide resident-info"><PageIntro title="How Party in a Box works" text="Plan an Oak Park block party in one place: check your block, gather neighbor signatures, and follow its status." action={<Button onClick={() => go('/resident/new')}>Start a new event</Button>} /><h2>Using the site</h2><div className="steps-card">{[['1','Check your block','Find out whether your street can close.'],['2','Pick dates','See what is due and when.'],['3','Share petition','Gather signatures from neighbors.'],['4','Submit and track','Follow Public Works review.'],['5','Party day','Review approved arrangements.']].map(([number, heading, detail]) => <div className="how-step" key={number}><span>{number}</span><h3>{heading}</h3><p>{detail}</p></div>)}</div><div className="info-grid"><Card><div className="section-heading"><h2>Block party rules</h2><small>Rules are supplied by Public Works</small></div>{rules.loading ? <LoadingCard label="Loading current rules…" /> : rules.error ? <ApiError message={rules.error} /> : <div className="rules-grid">{ruleRows.map((rule) => <div key={rule}><b>Requirement</b><p>{rule}</p></div>)}</div>}</Card><Card className="resources"><h2>Permit resources</h2><a href="https://www.oak-park.us/Community/Events-and-Activities/Block-Parties-and-Sales" target="_blank">Block parties page</a><p>Rules and forms from the Village.</p><b>Public Works</b><a href="mailto:publicworks@oak-park.us">publicworks@oak-park.us</a><a href="tel:+17083585700">708.358.5700</a></Card></div><Card className="faq"><h2>Frequently asked questions</h2>{['Is this the official Village application?','Why can’t my street be closed?','When is my petition due?','How do vendors work?'].map((question, index) => <details key={question} open={index === 0}><summary>{question}</summary><p>{index === 0 ? 'This interface connects to the Party in a Box service; Public Works rules and decisions are provided by the connected backend.' : 'The latest answer is determined by the rules and request data returned by Public Works.'}</p></details>)}</Card></div>;
}

function NewEvent({ go }: { go: (route: string) => void }) {
  const [address, setAddress] = useState(''); const [block, setBlock] = useState<RecordValue>(); const [error, setError] = useState(''); const [checking, setChecking] = useState(false);
  const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [guests, setGuests] = useState(''); const [saving, setSaving] = useState(false);
  const check = async () => { setChecking(true); setError(''); setBlock(undefined); try { const result = asRecord(await residentApi.lookupBlock(address)); setBlock(asRecord(result.block)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to check this block.'); } finally { setChecking(false); } };
  const save = async () => { if (!block?.id || !start || !end || !guests) return; setSaving(true); setError(''); try { const created = asRecord(await residentApi.createRequest({ block_id: text(block.id), date_start: start as `${number}-${number}-${number}`, date_end: end as `${number}-${number}-${number}`, guests: Number(guests), services: { barricades: true, green_kit: true } })); const requestId = text(created.id, ''); if (requestId) go(`/resident/petition/${requestId}`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save the request.'); } finally { setSaving(false); } };
  return <div className="wide new-event"><PageIntro title="Plan a new block party" text="Check your block, pick your dates, and see what is due when." /><EventStepper current={1} /><div className="new-grid"><div><h2>1. Check your block</h2><Card><div className="field-row"><label>Street address in Oak Park<input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="1100 S Cuyler Ave" /></label><Button onClick={check} disabled={!address || checking}>{checking ? 'Checking…' : 'Check block'}</Button></div><RealMap block={block} height={240} />{error && <ApiError message={error} />}{block && <BlockPacket block={block} />}</Card></div><aside><Card><h2>Village rules checklist</h2><ul className="checklist"><li>Street must be eligible for a closure.</li><li>Petition requires separate addresses.</li><li>Petition must be submitted in time.</li><li>Dates must fall within the current season.</li></ul></Card></aside></div>{block?.eligible === true && <div className="form-area"><h2>2. Pick dates and services</h2><Card><div className="form-grid"><label>Earliest date<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Latest date<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label><label>Expected guests<input type="number" min="1" value={guests} onChange={(event) => setGuests(event.target.value)} /></label></div><fieldset><legend>Services</legend><label className="service-check"><input type="checkbox" defaultChecked /><span><b>Barricades</b><small>Delivery timing is confirmed by Public Works.</small></span></label><label className="service-check"><input type="checkbox" defaultChecked /><span><b>Green Block Party kit</b><small>Recycling and compost setup.</small></span></label></fieldset><div className="button-row"><Button onClick={save} disabled={saving || !start || !end || !guests}>{saving ? 'Saving…' : 'Save and set up petition'}</Button></div></Card></div>}</div>;
}

function EventStepper({ current }: { current: number }) { return <ol className="event-stepper">{[['Fill in permit','Block, dates, services'],['Set up petition','Share a link, addresses'],['Submit permit','Sent to Public Works'],['Permit status','Track the review'],['Approved','Date and arrangements'],['Vendor matches','Automatic once approved']].map(([name, detail], index) => <li className={index + 1 === current ? 'current' : ''} key={name}><span>{index + 1}</span><b>{name}</b><small>{detail}</small></li>)}</ol>; }
function BlockPacket({ block }: { block: RecordValue }) { const eligible = block.eligible === true; return <div className={`block-result ${eligible ? 'eligible' : 'ineligible'}`}><b>{eligible ? `Eligible: ${text(block.label, text(block.name))}` : 'This block is not eligible'}</b><p>{text(block.reason, eligible ? 'This block is available for a party closure.' : 'Public Works has marked this block ineligible.')}</p>{Boolean(block.nearest_eligible) && <p>Nearest eligible block: {text(asRecord(block.nearest_eligible).label, JSON.stringify(block.nearest_eligible))}</p>}</div>; }

function Petition({ id, go }: { id: string; go: (route: string) => void }) {
  const requestState = useApi(() => request<unknown>(`/requests/${encodeURIComponent(id)}`), [id]);
  const requestData = asRecord(requestState.data); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const submit = async () => { setSubmitting(true); setError(''); try { await residentApi.submitRequest(id); go('/resident/events'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to submit the permit.'); } finally { setSubmitting(false); } };
  return <div className="wide petition"><PageIntro title="Get your neighbors’ signatures" text="Share the official petition link and track the count returned by the service." /><EventStepper current={2} />{requestState.loading ? <LoadingCard label="Loading petition…" /> : requestState.error ? <ApiError message={requestState.error} /> : <Card><h2>{text(requestData.block_label, text(asRecord(requestData.block).label, 'Block party request'))}</h2><p>{dateText(requestData.date_start)} – {dateText(requestData.date_end)}</p><div className="petition-progress"><strong>{text(requestData.distinct_count, '0')} <small>of {text(requestData.needed, '10')} addresses</small></strong><span>Signatures are private. The organizer can only see records returned by the backend.</span></div><div className="button-row"><Button variant="secondary" onClick={() => navigator.clipboard?.writeText(`${location.origin}${location.pathname}#/resident/petition/${id}`)}>Copy petition link</Button><Button onClick={submit} disabled={submitting}>{submitting ? 'Submitting…' : 'Submit permit request'}</Button></div>{error && <ApiError message={error} />}</Card>}</div>;
}

function MyEvents({ go }: { go: (route: string) => void }) {
  const state = useApi(() => residentApi.myRequests(), []); const items = records(state.data);
  return <div className="wide my-events"><PageIntro title="My events" text="Requests and approval statuses are loaded from the Party in a Box service." action={<Button onClick={() => go('/resident/new')}>New event</Button>} />{state.loading ? <LoadingCard label="Loading your events…" /> : state.error ? <ApiError message={state.error} /> : items.length ? items.map((item) => <EventCard item={item} key={text(item.id)} />) : <Card><h2>No events yet</h2><p>Start a new request to see it here.</p></Card>}</div>;
}
function EventCard({ item }: { item: RecordValue }) { return <Card className="event-card"><small>BLOCK PARTY · REQUEST {text(item.id).toUpperCase()}</small><div className="card-title"><h2>{text(item.block_label, text(asRecord(item.block).label, 'Oak Park block'))}</h2><Status value={item.status} /></div><EventStepper current={item.status === 'approved' ? 5 : 3} /><div className="event-detail-grid"><div><h3>Your date</h3><p>{dateText(item.approved_date ?? item.date_start)} · 9 a.m. – 11 p.m.</p><dl><div><dt>Barricades arrive</dt><dd>{dateText(item.barricade_date, 'Pending approval')}</dd></div><div><dt>Green Block Party kit</dt><dd>{asRecord(item.services).green_kit ? 'Requested' : 'Not requested'}</dd></div></dl></div><div><h3>Matched vendors</h3>{records(item.vendors).length ? records(item.vendors).map((vendor) => <div className="vendor-line" key={text(vendor.id, text(vendor.name))}><b>{text(vendor.name)}</b><span>{text(vendor.service)} · {text(vendor.includes)}</span><Status value={vendor.state} /></div>) : <p className="muted">Vendor matches appear after approval.</p>}</div></div></Card>; }

function Vendor({ route, go }: { route: string; go: (route: string) => void }) { if (route === '/vendor/matches') return <VendorMatches />; if (route === '/vendor/jobs') return <VendorJobs />; return <VendorHome go={go} />; }
function VendorHome({ go }: { go: (route: string) => void }) { const [me, offer, summary] = [useApi(() => vendorApi.me(), []), useApi(() => vendorApi.offer(), []), useApi(() => vendorApi.summary(), [])]; const account = asRecord(me.data); const currentOffer = asRecord(offer.data); return <div className="wide vendor-home"><PageIntro title="Your offer" text="Set up the standing offer Public Works uses for matching." />{me.loading || offer.loading ? <LoadingCard label="Loading vendor account…" /> : me.error || offer.error ? <ApiError message={me.error ?? offer.error ?? 'Unable to load the vendor account.'} /> : <><Status value={account.status} /><Card><div className="form-grid vendor-form"><label>Service<input value={text(currentOffer.service, '')} readOnly /></label><label>Price per event $<input value={text(currentOffer.price_usd, '')} readOnly /></label><label>Most guests you can serve<input value={text(currentOffer.max_guests, '')} readOnly /></label><label>Jobs per day<input value={text(currentOffer.jobs_per_day, '')} readOnly /></label><label className="full">What’s included<textarea value={text(currentOffer.includes, '')} readOnly /></label></div><Button variant="secondary">Edit offer</Button></Card><Card className="matching-explainer"><h2>How matching works</h2><ol><li>Public Works approves a block party.</li><li>Matching checks your service, availability, area, and capacity.</li><li>You choose whether to accept the job.</li></ol>{summary.loading ? <LoadingCard label="Loading counts…" /> : summary.error ? <ApiError message={summary.error} /> : <div className="right-now"><span>Right now</span><button onClick={() => go('/vendor/matches')}>{text(asRecord(summary.data).matched_open, '0')} matched jobs</button><button onClick={() => go('/vendor/jobs')}>{text(asRecord(summary.data).accepted, '0')} accepted jobs</button></div>}</Card></>}</div>; }
function VendorMatches() { const state = useApi(() => vendorApi.matches(), []); const jobs = records(state.data); return <div className="wide jobs"><PageIntro title="Matched jobs" text="Approved block parties that fit your offer. You decide which ones to take." />{state.loading ? <LoadingCard /> : state.error ? <ApiError message={state.error} /> : jobs.length ? jobs.map((job) => <Card className="job-card" key={text(job.match_id)}><h2>{text(job.block_label)} <small>({text(job.zip)})</small></h2><p>{dateText(job.date)} · {text(job.hours)}</p><dl><div><dt>Guests expected</dt><dd>{text(job.guests)}</dd></div><div><dt>Your price</dt><dd>${text(job.price)}</dd></div></dl><p className="match-reason">{list(job.why).join(' ')}</p><Button>Accept job</Button><Button variant="secondary">Decline</Button></Card>) : <Card><h2>All caught up</h2><p>There are no matching jobs at the moment.</p></Card>}</div>; }
function VendorJobs() { const state = useApi(() => vendorApi.jobs(), []); const jobs = records(state.data); return <div className="wide jobs"><PageIntro title="My jobs" text="Jobs you accepted. The organizer can see that you are coming." />{state.loading ? <LoadingCard /> : state.error ? <ApiError message={state.error} /> : jobs.length ? jobs.map((job) => <Card className="accepted-job" key={text(job.match_id)}><div className="calendar-tile"><b>{text(job.event_date).slice(5,7)}</b><strong>{text(job.event_date).slice(8,10)}</strong></div><div><h2>{text(job.block_label)}</h2><p>{dateText(job.event_date)} · {text(job.hours)} · {text(job.guests)} guests</p><Button variant="secondary">Message organizer</Button><Button variant="danger">Withdraw</Button></div></Card>) : <Card><h2>No accepted jobs yet</h2></Card>}</div>; }

function Village({ route }: { route: string; go: (route: string) => void }) { if (route === '/village/today') return <Today />; if (route === '/village/planner') return <Planner />; return <VillageRequests />; }
function VillageRequests() { const state = useApi(() => villageApi.requests(), []); const payload = asRecord(state.data); const queue = records(payload.requests ?? state.data); return <div className="wide requests"><PageIntro title="Block party requests" text="Requests are shown oldest first; approvals remain first come, first served." />{state.loading ? <LoadingCard label="Loading request queue…" /> : state.error ? <ApiError message={state.error} /> : <div className="request-grid"><div className="request-list">{queue.map((item) => <button key={text(item.id)}><div><b>{text(item.block_label)}</b><Status value={item.status} /></div><span>{dateText(item.date_start)} – {dateText(item.date_end)}</span><small>Petition {text(item.distinct_count)}/{text(item.needed, '10')} · Impact: {text(item.level)}</small></button>)}</div><Card className="request-detail"><h2>Select a request</h2><p>Request details, approval gates, candidate dates, and messages are loaded after selecting an item from the queue.</p></Card></div>}</div>; }
function Today() { const state = useApi(() => villageApi.today('2027-06-19'), []); const payload = asRecord(state.data); const parties = records(payload.parties); return <div className="wide today"><PageIntro title="Today" text="Approved parties and their rule-based traffic impact." /><RealMap height={340} />{state.loading ? <LoadingCard label="Loading today’s closures…" /> : state.error ? <ApiError message={state.error} /> : <><div className="today-stats"><Card><b>Block parties today</b><strong>{text(asRecord(payload.totals).count, '0')}</strong></Card><Card><b>Traffic impact</b><strong>{JSON.stringify(asRecord(payload.totals).by_level ?? {})}</strong></Card><Card><b>Bus stops on closed blocks</b><strong>{text(asRecord(payload.totals).bus_stops_closed, '0')}</strong></Card><Card><b>Vendors serving today</b><strong>{text(asRecord(payload.totals).vendors, '0')}</strong></Card></div><div className="today-list">{parties.map((party) => <Card key={text(party.block_label)}><div><h3>{text(party.block_label)}</h3><p>{text(party.hours)} · {text(party.guests)} guests <Status value={party.level} /> {list(party.why).join(' ')}</p></div></Card>)}</div></>}</div>; }
function Planner() { const [weekday, setWeekday] = useState(false); const [question, setQuestion] = useState(''); const [result, setResult] = useState<unknown>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const ask = async () => { setLoading(true); setError(''); try { setResult(await villageApi.whatIf('2027-06-19', [], weekday)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to run the planner.'); } finally { setLoading(false); } }; const answer = asRecord(result); return <div className="wide planner"><PageIntro title="Traffic planner" text="Test a closure scenario. The backend calculates scores; this interface only displays them." /><Card className="planner-ask"><div><b>Day type</b><label className="inline-check"><input type="radio" checked={!weekday} onChange={() => setWeekday(false)} />Saturday</label><label className="inline-check"><input type="radio" checked={weekday} onChange={() => setWeekday(true)} />A weekday</label></div><div className="ask-row"><label>Ask the traffic planner<input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about closures" /></label><Button onClick={ask} disabled={loading}>{loading ? 'Checking…' : 'Ask'}</Button></div></Card><div className="planner-grid"><Card className="assistant-answer"><h2>Planner result</h2>{error ? <ApiError message={error} /> : result ? <><p>{text(answer.summary, 'The backend returned a scenario result.')}</p><dl><div><dt>Highest impact</dt><dd>{text(asRecord(answer.worst).level)} · {text(asRecord(answer.worst).score)}</dd></div><div><dt>Weekend count</dt><dd>{text(answer.weekend_count)}</dd></div></dl></> : <p className="muted">Run a scenario to see a backend-calculated result.</p>}</Card><Card className="planner-map"><h2>Map</h2><RealMap height={330} /><p className="legend">Uses OpenStreetMap. Closure geometry is drawn from the backend once a scenario returns it.</p></Card></div></div>; }

export default App;
